name: Compilar EXE de Windows con GraalVM

# ¿Cuándo se ejecuta esto? 
# Cada vez que hagas un 'git push' o manualmente desde la web.
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    # ¡Aquí le pedimos prestada a GitHub una máquina con Windows!
    runs-on: windows-latest 

    steps:
      # 1. Descarga tu código (el jar y la carpeta de config) en la máquina virtual
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # 2. Instala GraalVM mágicamente en segundos
      - name: Configurar GraalVM 25
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # 3. Compilar el ejecutable
      - name: Compilar JAR a EXE nativo
        run: |
          native-image -jar clima.jar -H:ConfigurationFileDirectories=configuracion -H:IncludeLocales=es -H:NativeLinkerOption=/SUBSYSTEM:WINDOWS -H:NativeLinkerOption=/ENTRY:mainCRTStartup --no-fallback

      # 4. Robar los archivos de fuentes del JDK de Microsoft
      - name: Extraer configuración de fuentes
        run: |
          New-Item -ItemType Directory -Force -Path lib
          Copy-Item "$env:JAVA_HOME\lib\fontconfig.*" -Destination lib\

      # 5. Guardar el .exe, las DLLs y la carpeta lib
      - name: Subir el ejecutable y librerías
        uses: actions/upload-artifact@v4
        with:
          name: ClimaApp-Windows
          path: |
            clima.exe
            *.dll
            lib/
